services:
  wg-easy:
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy

    environment:
      - $$2a$$12$$82QcX.b3dPEHYxgtM6Y.4.J2EMOI4rgryBjkNSrNGzN5ZJkPEiS/u
      - WG_HOST=vpn.threelakes.us

    volumes:
      - /opt/containers/wireguard/config:/etc/wireguard
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
